### ISSUE TITLE
Help! ('_imaging' from 'PIL' error) in Lambda

### ISSUE THREAD

**Issue by PremKumarSharma1867** [PremKumarSharma1867/pywhatkit-for-Lambda#1]
Hi,
 
Hope you are doing well!
 
Can you please help in fixing python “PIL” error when I am calling it from AWS Lambda? This will help me a lot.
 
The code (given below) works fine in pycharm (python version 3.10). But I am getting below error when I call PIL in Lambda:
 
[ERROR] Runtime.ImportModuleError: Unable to import module 'lambda_function': cannot import name '_imaging' from 'PIL' (/opt/python/PIL/__init__.py)

Code that I am running:

import pywhatkit
import pyautogui
import datetime
import time

def send_whatsapp_msg(v_mobile, v_country_code, v_msg):
   
    pywhatkit.sendwhatmsg_instantly(v_country_code+v_mobile, v_msg, 10)
    
    time.sleep(2)   # Give 2 seconds time before pressing ENTER Key
    pyautogui.press("enter")    # Press ENTER Key
    pyautogui.press("enter")    # Press ENTER Key again for safer side
    
    return True

Thanks in advance!
Best Regards,
Prem Sharma  (he/him)
